apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: webserver1
      image: httpd
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
  tolerations:
  - key: "prod"
    operator: "Equal"  #
    value: "yes"
    effect: "NoSchedule" 